version: "3"
services:
  jobmanager:
    image: flink-cdc
    build:
      context: ./
    expose:
      - "6123"
    ports:
      - "8081:8081"
      - "8082:8082"
    command: jobmanager
    volumes:
      - ./completed-jobs:/opt/flink/completed-jobs
    environment:
      #- JOB_MANAGER_RPC_ADDRESS=jobmanager
      - TZ=Asia/Taipei
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        jobmanager.archive.fs.dir: file:///opt/flink/completed-jobs/
        historyserver.archive.fs.dir: file:///opt/flink/completed-jobs/
        historyserver.archive.fs.refresh-interval: 10000   

  taskmanager:
    image: flink-cdc
    build:
      context: ./
    expose:
      - "6121"
      - "6122"
    depends_on:
      - jobmanager
    command: taskmanager
    links:
      - "jobmanager:jobmanager"
    environment:
      - TZ=Asia/Taipei
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        taskmanager.numberOfTaskSlots: 5 

