version: "3"
services:
  jobmanager:
    image: flink-cdc
    build:
      context: ./
    expose:
      - "6123"
    ports:
      - "8081:8081"
    command: jobmanager
    environment:
      - JOB_MANAGER_RPC_ADDRESS=jobmanager
      - TZ=Asia/Taipei

  taskmanager:
    image: flink-cdc
    build:
      context: ./
    expose:
      - "6121"
      - "6122"
    depends_on:
      - jobmanager
    command: taskmanager
    links:
      - "jobmanager:jobmanager"
    environment:
      - TZ=Asia/Taipei
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        taskmanager.numberOfTaskSlots: 3

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.5
    hostname: elasticsearch
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xmx512m -Xms512m"
      DISCOVERY.TYPE: "single-node"
      cluster.initial_master_nodes: "elasticsearch"
      cluster.name: "elasticsearch"
      bootstrap.memory_lock: 'false'
      #ELASTIC_PASSWORD: 'changeme'
      xpack.security.enabled: 'false'
      xpack.ml.enabled: 'false'

  kibana:
    image: docker.elastic.co/kibana/kibana:7.17.5
    ports:
      - "5601:5601"
    environment:
      SERVER_HOST: "0.0.0.0"
      ELASTICSEARCH_HOSTS: 'http://elasticsearch:9200'

  oracle:
    image: yuxialuo/oracle-xe-11g-r2-cdc-demo:v1.0
    ports:
      - "1521:1521"

